#### Layer 5 — Synthesize

*What combination of factors best explains the spending-outcome gap?*

*Can hospitals be grouped into meaningful archetypes based on their spending and quality profile?*

In [1]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("../cms_hospital.db")
paradox_hospitals = pd.read_csv('../outputs/paradox_hospitals.csv')
paradox_hospitals['facility_id'] = paradox_hospitals['facility_id'].astype(str).str.zfill(6)

print(f"Loaded {len(paradox_hospitals)} paradox hospitals")

Loaded 99 paradox hospitals


In [3]:
summary_data = {
    'Dimension': [
        'Avg Spending per Episode',
        'Composite Outcome Score',
        'HAI Infection Rate (avg SIR)',
        'EDAC Heart Failure (excess days)',
        'EDAC Pneumonia (excess days)',
        '30-day Readmissions',
        'HCAHPS Star Rating',
        'Discharge Info Score',
        'Hospital Type',
        'States Most Affected'
    ],
    'Paradox Hospitals': [
        '$29,059',
        'Negative (below 0)',
        'Above 1.0 on 5 of 6 measures',
        '12.893 days',
        '17.988 days',
        'Marginal difference',
        '2.42 / 5',
        '73.06',
        '100% Acute Care',
        'KY 6.9%, AR 6.7%, NJ 5.1%'
    ],
    'All Other Hospitals': [
        '$25,574',
        'Positive (above 0)',
        'Below 1.0 on most measures',
        '4.918 days',
        '5.871 days',
        'Marginal difference',
        '3.27 / 5',
        '76.58',
        'Mixed types',
        'Distributed evenly'
    ],
    'Verdict': [
        ' +$3,485 more per patient',
        ' Consistently underperforming',
        ' 2x worse than peers',
        ' 2.6x worse than peers',
        ' 3x worse than peers',
        ' Not a primary driver',
        ' -0.85 stars lower',
        ' Poor discharge planning',
        ' Fully resourced, no excuse',
        ' Smaller states, bigger problem'
    ]
}

master_table = pd.DataFrame(summary_data)
master_table

,Dimension,Paradox Hospitals,All Other Hospitals,Verdict
0,Avg Spending per Episode,"$29,059","$25,574","+$3,485 more per patient"
1,Composite Outcome Score,Negative (below 0),Positive (above 0),Consistently underperforming
2,HAI Infection Rate (avg SIR),Above 1.0 on 5 of 6 measures,Below 1.0 on most measures,2x worse than peers
3,EDAC Heart Failure (excess days),12.893 days,4.918 days,2.6x worse than peers
4,EDAC Pneumonia (excess days),17.988 days,5.871 days,3x worse than peers
5,30-day Readmissions,Marginal difference,Marginal difference,Not a primary driver
6,HCAHPS Star Rating,2.42 / 5,3.27 / 5,-0.85 stars lower
7,Discharge Info Score,73.06,76.58,Poor discharge planning
8,Hospital Type,100% Acute Care,Mixed types,"Fully resourced, no excuse"
9,States Most Affected,"KY 6.9%, AR 6.7%, NJ 5.1%",Distributed evenly,"Smaller states, bigger problem"


In [5]:
master_table.to_csv('../outputs/layer5_master_summary.csv', index=False)
print("Saved to outputs/layer5_master_summary.csv")

Saved to outputs/layer5_master_summary.csv


# Layer 5 — Synthesis: The Full Picture


## The Evidence at a Glance

*See master_table above*



## Two Hospital Archetypes

The American hospital system is not monolithic.
Across the CMS dataset, two fundamentally different profiles emerge.


###  The Dysfunction Trap
*The 99 paradox hospitals*

These are fully equipped Acute Care facilities.
They have the staff, the technology, the budget.
They are not small rural hospitals struggling with limited resources.
They are not overwhelmed by unusually complex patients —
CMS already risk-adjusts for that.

Yet something goes wrong inside them.

A patient arrives. The stay extends beyond what is clinically expected.
During that extended stay, the risk of infection compounds daily.
HAI rates run 2x higher than peers — not because infections are inevitable,
but because the processes that prevent them are failing.
The patient gets worse. The stay gets longer.
The hospital is now legally required to keep treating
a problem it created.

When the patient finally leaves, they are not fully stabilized.
Within 30 days they end up in a skilled nursing facility
or back in a hospital bed — generating another 1,000 dollar in costs
that follow them out the door.

The spending is not investment. It is consequence.
3,485 dollars more per patient. Worse outcomes. Lower satisfaction.
A 2.42 star rating from patients who felt something was off
but couldn't name exactly what.

**The Dysfunction Trap is not a funding problem.
It is a process problem dressed up as a spending problem.**


###  The Efficient Performer
*The benchmark these 99 hospitals should be measured against*

These hospitals are not necessarily the cheapest or the most famous.
They are the ones that figured out the fundamentals:

Patients are stabilized properly and discharged on time.
Infection prevention protocols are followed consistently.
Discharge planning begins on day one, not the day before leaving.
Care transitions are coordinated — the patient goes home
or to the right facility at the right moment.

The result: EDAC rates 2-3x lower, HAI rates below the national benchmark,
spending at or below average, and clinical outcomes that beat
the national rate on most measures.

These hospitals prove that the paradox is not inevitable.
Good outcomes and controlled spending are achievable —
not through more money, but through better processes.


## The Answer to the Central Research Question

> **Why is hospital spending not linearly related to clinical outcomes —
> and what explains the hospitals that spend more but achieve worse results?**

The answer, built layer by layer across this analysis:

**Spending does not drive outcomes. Process quality does.**

The 99 paradox hospitals spend 3,485 dollars more per patient than their peers
not because they are investing in better care —
but because their internal process failures generate cascading costs
that no amount of money can retroactively fix.

The mechanism is clear:
1. Poor care coordination → patients stay longer than necessary
2. Extended stays → higher infection exposure
3. Hospital-acquired infections → complications, further extended stays
4. Poor discharge planning → patients leave unstabilized
5. Unstabilized patients → readmissions, skilled nursing costs
6. All of the above → higher spending, worse outcomes, lower satisfaction

The correlation between spending and outcomes is only 0.24 —
meaning 76% of what determines whether a hospital performs well
has nothing to do with how much money it spends.

**The hospitals that spend the most on dysfunction
are the hospitals that invest the least in process.**

That is the paradox.
That is the finding.
And it is a policy problem hiding in plain sight
inside the CMS data that was always there to be read.